version: 2
updates:
  # Python deps (server)
  - package-ecosystem: "pip"
    directory: "/server"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(server)"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(ci)"
